version: '3.2'
services:
    nginx:
        build:
            context: ./.docker/nginx
            args:
                PROJECT_NAME: ${PROJECT_NAME}
                PROJECT_DOMEN: ${PROJECT_DOMEN}

        image: docker/nginx

        container_name: nginx-${PROJECT_NAME}

        volumes:
            - ./.docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/logs/nginx:/var/log/nginx
            - ./:/var/www/${PROJECT_DOMEN}

        ports:
            - 80:80
            - 443:443

        depends_on:
            - php

        networks:
            - docker-network

    php:
        build:
            context: ./.docker/php
            args:
                PROJECT_NAME: ${PROJECT_NAME}
                PROJECT_DOMEN: ${PROJECT_DOMEN}

        image: docker/php

        container_name: php-${PROJECT_NAME}

        volumes:
            - ./.docker/php/conf/php.ini:/usr/local/etc/php/php.ini
            - ./.docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./.docker/php/conf/settings.pool.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./.docker/logs/php:/usr/local/var/log
            - ./:/var/www/${PROJECT_DOMEN}

        ports:
            - 9001:9000

        depends_on:
            - mariadb

        networks:
            - docker-network

    mariadb:
        image: mariadb

        container_name: mariadb-${PROJECT_NAME}

        ports:
            - 3300:3306

        restart: always

        volumes:
            - ./.docker/data/mariadb:/var/lib/mysql
            - ./.docker/logs/mariadb:/var/log/mysql

        environment:
           MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
           MYSQL_DATABASE: ${MYSQL_DATABASE}
           MYSQL_USER: ${MYSQL_USER}
           MYSQL_PASSWORD: ${MYSQL_PASSWORD}

        networks:
            - docker-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin

        container_name: phpmyadmin-${PROJECT_NAME}

        ports:
            - 8080:80

        restart: always

        environment:
            PMA_HOST: mariadb-${PROJECT_NAME}

        depends_on:
            - mariadb

        networks:
            - docker-network

networks:
    docker-network:
        driver: bridge
